import mysql.connector
from mysql.connector import Error

# 常用动漫日文->中文名称映射
anime_name_map = {
    'Sousou no Frieren': '葬送的芙莉莲',
    'Frieren: Beyond Journey\'s End': '葬送的芙莉莲',
    'Fullmetal Alchemist: Brotherhood': '钢之炼金术师FA',
    'Steins;Gate': '命运石之门',
    'Hunter x Hunter (2011)': '全职猎人',
    'Bleach: Sennen Kessen-hen': '死神 千年血战篇',
    'Ginga Eiyuu Densetsu': '银河英雄传说',
    'Monster': '怪物',
    'Gintama': '银魂',
    'Shingeki no Kyojin Season 3 Part 2': '进击的巨人 第三季',
    'Shingeki no Kyojin': '进击的巨人',
    'Attack on Titan': '进击的巨人',
    'One Piece': '海贼王',
    'Kimetsu no Yaiba': '鬼灭之刃',
    'Demon Slayer': '鬼灭之刃',
    'Sen to Chihiro no Kamikakushi': '千与千寻',
    'Spirited Away': '千与千寻',
    'Death Note': '死亡笔记',
    'Cowboy Bebop': '星际牛仔',
    'Vinland Saga Season 2': '冰海战记 第二季',
    'Vinland Saga': '冰海战记',
    'Code Geass: Hangyaku no Lelouch': '反叛的鲁路修',
    'Great Teacher Onizuka': '麻辣教师GTO',
    'Hajime no Ippo': '第一神拳',
    'Howl no Ugoku Shiro': '哈尔的移动城堡',
    'Mononoke Hime': '幽灵公主',
    'Mushishi': '虫师',
    'Mo Dao Zu Shi': '魔道祖师',
    'Tengen Toppa Gurren Lagann': '天元突破 红莲螺岩',
    'Shigatsu wa Kimi no Uso': '四月是你的谎言',
    'Tian Guan Cifu': '天官赐福',
    'Natsume Yuujinchou': '夏目友人帐',
    'Ping Pong the Animation': '乒乓',
    'Odd Taxi': '奇巧计程车',
    'Shiguang Dailiren': '时光代理人',
    'Luo Xiao Hei Zhan Ji': '罗小黑战记',
    'Made in Abyss': '来自深渊',
    'Cyberpunk: Edgerunners': '赛博朋克：边缘行者',
    'Haikyuu!!': '排球少年',
    'Jujutsu Kaisen': '咒术回战',
    'Bungou Stray Dogs': '文豪野犬',
    'Dungeon Meshi': '迷宫饭',
    'Suzumiya Haruhi no Shoushitsu': '凉宫春日的消失',
    'Mushoku Tensei': '无职转生',
    'Kenpuu Denki Berserk': '剑风传奇',
    'Alien Stage': '异形舞台',
    'Seishun Buta Yarou': '青春猪头少年不会梦到兔女郎学姐',
    'Nana': '娜娜',
    'Kaguya-sama wa Kokurasetai': '辉夜大小姐想让我告白',
    'Oshi no Ko': '我推的孩子',
    'Bocchi the Rock!': '孤独摇滚',
    'Chainsaw Man': '电锯人',
    'Spy x Family': '间谍过家家',
    'Blue Lock': '蓝色监狱',
    'Ao no Exorcist': '青之驱魔师',
    'Sword Art Online': '刀剑神域',
    'Tokyo Ghoul': '东京食尸鬼',
    'Naruto': '火影忍者',
    'Naruto Shippuuden': '火影忍者 疾风传',
    'My Hero Academia': '我的英雄学院',
    'Dr. Stone': '石纪元',
    'Re:Zero kara Hajimeru Isekai Seikatsu': 'Re:从零开始的异世界生活',
    'Kono Subarashii Sekai ni Shukufuku wo!': '为美好的世界献上祝福!',
    'Overlord': '不死者之王',
    'That Time I Got Reincarnated as a Slime': '关于我转生变成史莱姆这档事',
    'Mob Psycho 100': '灵能百分百',
    'One Punch Man': '一拳超人',
    'JoJo no Kimyou na Bouken': 'JOJO的奇妙冒险',
    'Psycho-Pass': '心理测量者',
    'No Game No Life': '游戏人生',
    'Toradora!': '龙与虎',
    'Clannad': '团子大家族',
    'Angel Beats!': '天使的心跳',
    'A Silent Voice': '声之形',
    'Koe no Katachi': '声之形',
    'Kimi no Na wa.': '你的名字',
    'Your Name': '你的名字',
    'Weathering With You': '天气之子',
    'Tenki no Ko': '天气之子',
    '5 Centimeters per Second': '秒速5厘米',
    'Neon Genesis Evangelion': '新世纪福音战士',
    'Evangelion': '新世纪福音战士',
    'Ghost in the Shell': '攻壳机动队',
    'Akira': '阿基拉',
    'Princess Mononoke': '幽灵公主',
    'Howl\'s Moving Castle': '哈尔的移动城堡',
    'Grave of the Fireflies': '萤火虫之墓',
    'Perfect Blue': '未麻的部屋',
    'Paprika': '红辣椒',
    'Tokyo Godfathers': '东京教父',
    'Parasyte': '寄生兽',
    'Kiseijuu': '寄生兽',
    'The Tatami Galaxy': '四叠半神话大系',
    'Slam Dunk': '灌篮高手',
    'Inuyasha': '犬夜叉',
    'Detective Conan': '名侦探柯南',
    'Case Closed': '名侦探柯南',
    'Pokemon': '宝可梦',
    'Digimon Adventure': '数码宝贝',
    'Yu Yu Hakusho': '幽游白书',
    'Rurouni Kenshin': '浪客剑心',
    'Trigun': '枪神',
    'Black Lagoon': '黑礁',
    'Hellsing Ultimate': '皇家国教骑士团',
    'Durarara!!': '无头骑士异闻录',
    'Baccano!': '永生之酒',
    'Monogatari': '物语系列',
    'Bakemonogatari': '化物语',
    'Mahou Shoujo Madoka Magica': '魔法少女小圆',
    'Puella Magi Madoka Magica': '魔法少女小圆',
    'Fate/Zero': '命运零点',
    'Fate/stay night': '命运守护夜',
    'Goblin Slayer': '哥布林杀手',
    'Mirai Nikki': '未来日记',
    'Future Diary': '未来日记',
    'Another': '替身',
    'Erased': '只有我不存在的城市',
    'Boku dake ga Inai Machi': '只有我不存在的城市',
    'Steins;Gate 0': '命运石之门0',
    'Guilty Crown': '罪恶王冠',
    'Arcane': '英雄联盟：双城之战',
    'Castlevania': '恶魔城',
    'Devilman Crybaby': '恶魔人 哭泣之子',
    'Great Pretender': '大欺诈师',
    'Beastars': '动物狂想曲',
    'Aggretsuko': '冲吧烈子',
    'Hibike! Euphonium': '吹响！上低音号',
    'Sound! Euphonium': '吹响！上低音号',
    'Hanasaku Iroha': '花开伊吕波',
    'Shirobako': '白箱',
    'New Game!': 'NEW GAME!',
    'Working!!': '迷糊餐厅',
    'Wagnaria!!': '迷糊餐厅',
    'The Devil is a Part-Timer!': '打工吧！魔王大人',
    'Hataraku Maou-sama!': '打工吧！魔王大人',
    'The Daily Life of the Immortal King': '仙王的日常生活',
    'Link Click': '时光代理人',
    'Heaven Official\'s Blessing': '天官赐福',
    'Grandmaster of Demonic Cultivation': '魔道祖师',
    'The King\'s Avatar': '全职高手',
    'Fox Spirit Matchmaker': '狐妖小红娘',
    'Under One Person': '一人之下',
    'Hitori no Shita': '一人之下',
    'Spare Me, Great Lord!': '大王饶命',
    'Rakshasa Street': '镇魂街',
    'Soul Land': '斗罗大陆',
    'Battle Through the Heavens': '斗破苍穹',
    'Martial Universe': '武动乾坤',
    'Perfect World': '完美世界',
    'Stellar Transformations': '星辰变',
    'Swallowed Star': '吞噬星空',
    'Summer Time Rendering': '夏日重现',
    'Cyberpunk Edgerunners': '赛博朋克：边缘行者',
    'Jujutsu Kaisen Season 2': '咒术回战 第二季',
    'Demon Slayer Season 3': '鬼灭之刃 刀匠村篇',
    'Attack on Titan Final Season': '进击的巨人 最终季',
    'Suzume': '铃芽之旅',
    'Suzume no Tojimari': '铃芽之旅',
    'Belle': '龙和雀斑公主',
    'Ryuu to Sobakasu no Hime': '龙和雀斑公主',
    'Kimi no Suizou o Tabetai': '我想吃掉你的胰脏',
    'I Want to Eat Your Pancreas': '我想吃掉你的胰脏',
    'Anohana: The Flower We Saw That Day': '未闻花名',
    'Ano Hi Mita Hana no Namae o Bokutachi wa Mada Shiranai': '未闻花名',
    'Lovely Complex': '恋爱情结',
    'Maid Sama!': '会长是女仆大人',
    'Kaichou wa Maid-sama!': '会长是女仆大人',
    'Ouran High School Host Club': '樱兰高校男公关部',
    'Vampire Knight': '吸血鬼骑士',
    'Yuri on Ice': '冰上的尤里',
    'Free!': 'Free! 男子游泳部',
    'Diamond no Ace': '钻石王牌',
    'Ace of Diamond': '钻石王牌',
    'Food Wars!': '食戟之灵',
    'Shokugeki no Souma': '食戟之灵',
    'Kekkai Sensen': '血界战线',
    'Blood Blockade Battlefront': '血界战线',
    'Dimension W': '维度战记',
    'Granblue Fantasy': '碧蓝幻想',
    'Azur Lane': '碧蓝航线',
    'Kantai Collection': '舰队Collection',
    'KanColle': '舰娘',
    'Arknights': '明日方舟',
    'Girls Frontline': '少女前线',
    'Toaru Majutsu no Index': '魔法禁书目录',
    'A Certain Scientific Railgun': '某科学的超电磁炮',
    'Toaru Kagaku no Railgun': '某科学的超电磁炮',
    'Tengoku Daimakyou': '天国大魔境',
    'Heavenly Delusion': '天国大魔境',
    'Yamishibai': '暗芝居',
    'Junji Ito Collection': '伊藤润二精选集',
    'Uzumaki': '漩涡',
    'Tomo-chan wa Onnanoko!': '小智是女孩啦！',
    'Tomo-chan Is a Girl!': '小智是女孩啦！',
    'Ooyukiumi no Kaina': '大雪海的凯纳',
    'Kaina of the Great Snow Sea': '大雪海的凯纳',
    'Kyokou Suiri': '虚构推理',
    'In/Spectre': '虚构推理',
    'Jigokuraku': '地狱乐',
    'Hell\'s Paradise': '地狱乐',
    'Kimi wa Kanata': '你是彼方',
    'Over the Sky': '你是彼方',
    'Tenkuu no Shiro Laputa': '天空之城',
    'Castle in the Sky': '天空之城',
    'Kaze no Tani no Nausicaä': '风之谷',
    'Nausicaä of the Valley of the Wind': '风之谷',
    'Tonari no Totoro': '龙猫',
    'My Neighbor Totoro': '龙猫',
    'Majo no Takkyuubin': '魔女宅急便',
    'Kiki\'s Delivery Service': '魔女宅急便',
    'Omohide Poro Poro': '岁月的童话',
    'Only Yesterday': '岁月的童话',
    'Kurenai no Buta': '红猪',
    'Porco Rosso': '红猪',
    'Sento Chihiro no Kamikakushi': '千与千寻',
    'Hauru no Ugoku Shiro': '哈尔的移动城堡',
    'Gake no Ue no Ponyo': '崖上的波妞',
    'Ponyo': '崖上的波妞',
    'Kaguya-hime no Monogatari': '辉夜姬物语',
    'The Tale of the Princess Kaguya': '辉夜姬物语',
    'Kaze Tachinu': '起风了',
    'The Wind Rises': '起风了',
    'Hotaru no Haka': '萤火虫之墓',
    'Grave of the Fireflies': '萤火虫之墓',
    'Yamada-kun to 7-nin no Majo': '山田君与7人魔女',
    'Yamada-kun and the Seven Witches': '山田君与7人魔女',
    'Noragami': '野良神',
    'Stray God': '野良神',
    'Noragami Aragoto': '野良神  Aragoto',
    'Ao Haru Ride': '青春之旅',
    'Blue Spring Ride': '青春之旅',
    'Strobe Edge': '闪烁的爱情',
    'Sukitte Ii na yo': '只要你说你爱我',
    'Say I Love You': '只要你说你爱我',
    'Kimi ni Todoke': '好想告诉你',
    'From Me to You': '好想告诉你',
    'Bokura ga Ita': '我们的存在',
    'Bokura ga Ita': '我们的存在',
    'Peach Girl': '蜜桃女孩',
    'Kare Kano': '他和她的故事',
    'His and Her Circumstances': '他和她的故事',
    'Fruits Basket': '水果篮子',
    'Furuba': '水果篮子',
    'Rurouni Kenshin': '浪客剑心',
    'Samurai X': '浪客剑心',
    'Rurouni Kenshin: Meiji Kenkaku Romantan': '浪客剑心 -明治剑客浪漫谭-',
    'Gintama': '银魂',
    'Gintama.': '银魂.',
    'Gintama': '银魂',
    'Kuroko no Basket': '黑子的篮球',
    'Kuroko\'s Basketball': '黑子的篮球',
    'Yowamushi Pedal': '飙速宅男',
    'Weakling Pedal': '飙速宅男',
    'Days': 'DAYS',
    'Days (TV)': 'DAYS',
    'All Out!!': 'ALL OUT!!',
    'Cheer Boys!!': '男子啦啦队！！',
    'Backflip!!': '后空翻！！',
    'Bakuten!!': '后空翻！！',
    'Re-Main': 'RE-MAIN',
    'Skate-Leading Stars': '滑冰之星',
    'Skate-Leading ☆ Stars': '滑冰之星',
    'Salaryman\'s Club': '白领羽球部',
    'Ryman\'s Club': '白领羽球部',
    'Aoashi': '青之芦苇',
    'Blue Lock': '蓝色监狱',
    'Blue Lock': '蓝色监狱',
    'Captain Tsubasa': '足球小将',
    'Super Kickers': '足球小将',
    'Hungry Heart: Wild Striker': '野狼前锋',
    'Ginga e Kickoff!!': '向银河开球',
    'Inazuma Eleven': '闪电十一人',
    'Inazuma Eleven Go': '闪电十一人GO',
    'Inazuma Eleven: Ares no Tenbin': '闪电十一人 阿瑞斯的天秤',
    'Eyeshield 21': '光速跑者21号',
    'Hajime no Ippo': '第一神拳',
    'Fighting Spirit': '第一神拳',
    'Ashita no Joe': '明日之丈',
    'Tomorrow\'s Joe': '明日之丈',
    'Rock Lee no Seishun Full-Power Ninden': '李洛克的青春全力忍传',
    'Naruto SD': '火影忍者SD',
    'Boruto: Naruto Next Generations': '博人传：火影忍者新时代',
    'Naruto Shippuuden': '火影忍者 疾风传',
    'Naruto': '火影忍者',
    'One Piece': '海贼王',
    'One Piece: Stampede': '海贼王：狂热行动',
    'One Piece Film: Red': '海贼王：红发歌姬',
    'One Piece Film: Gold': '海贼王：黄金城',
    'One Piece Film: Z': '海贼王：Z',
    'One Piece Film: Strong World': '海贼王：强者天下',
    'Dragon Ball': '龙珠',
    'Dragon Ball Z': '龙珠Z',
    'Dragon Ball Kai': '龙珠改',
    'Dragon Ball Super': '龙珠超',
    'Dragon Ball GT': '龙珠GT',
    'Dragon Ball Heroes': '龙珠英雄',
    'Dragon Ball Super: Broly': '龙珠超：布罗利',
    'Dragon Ball Super: Super Hero': '龙珠超：超级英雄',
    'Yu-Gi-Oh!': '游戏王',
    'Yu-Gi-Oh! Duel Monsters': '游戏王 怪兽之决斗',
    'Yu-Gi-Oh! GX': '游戏王GX',
    'Yu-Gi-Oh! 5D\'s': '游戏王5D\'s',
    'Yu-Gi-Oh! Zexal': '游戏王ZEXAL',
    'Yu-Gi-Oh! Arc-V': '游戏王ARC-V',
    'Yu-Gi-Oh! VRAINS': '游戏王VRAINS',
    'Yu-Gi-Oh! Sevens': '游戏王SEVENS',
    'Yu-Gi-Oh! Go Rush!!': '游戏王GORUSH!!',
    'Beyblade': '战斗陀螺',
    'Beyblade G-Revolution': '战斗陀螺G',
    'Beyblade Metal Fusion': '战斗陀螺 钢铁奇兵',
    'Beyblade Burst': '战斗陀螺 爆裂世代',
    'Bakugan Battle Brawlers': '爆丸',
    'Bakugan': '爆丸',
    'Bakugan: New Vestroia': '爆丸2大爆破',
    'Bakugan: Gundalian Invaders': '爆丸3狩猎保卫者',
    'Bakugan: Mechtanium Surge': '爆丸4机械波涛',
    'Bakugan: Battle Planet': '爆丸：星域争霸',
    'Medabots': '徽章战士',
    'Medarot': '徽章战士',
    'Digimon Tamers': '数码宝贝驯兽师之王',
    'Digimon Frontier': '数码宝贝无限地带',
    'Digimon Savers': '数码宝贝拯救队',
    'Digimon Xros Wars': '数码宝贝合体战争',
    'Digimon Universe: Appli Monsters': '数码宝贝宇宙：应用怪兽',
    'Digimon Adventure (2020)': '数码宝贝大冒险：',
    'Digimon Ghost Game': '数码宝贝幽灵游戏',
    'Pokemon (2023)': '宝可梦 地平线',
    'Pokemon Horizons: The Series': '宝可梦 地平线',
    'Pocket Monsters': '宝可梦',
    'Pokemon Advanced Generation': '宝可梦 超世代',
    'Pokemon Diamond & Pearl': '宝可梦 钻石与珍珠',
    'Pokemon Best Wishes!': '宝可梦 超级愿望',
    'Pokemon XY': '宝可梦 XY',
    'Pokemon Sun & Moon': '宝可梦 太阳与月亮',
    'Pokemon Journeys': '宝可梦 旅途',
    'Pokemon Master Journeys': '宝可梦 新旅途',
    'Pokemon Ultimate Journeys': '宝可梦 最终旅途',
    'Shaman King': '通灵王',
    'Shaman King (2021)': '通灵王',
    'Zatch Bell!': '金童卡修',
    'Konjiki no Gash!!': '金童卡修',
    'D.Gray-man': '驱魔少年',
    'D.Gray-man Hallow': '驱魔少年 圣徒',
    'Katekyo Hitman Reborn!': '家庭教师',
    'Hitman Reborn': '家庭教师',
    'Tutor Hitman Reborn!': '家庭教师HITMAN REBORN!',
    'MÄR': '魔兵传奇',
    'MAR: Marchen Awakens Romance': '魔兵传奇',
    'Law of Ueki': '植木的法则',
    'Ueki no Housoku': '植木的法则',
    'Busou Renkin': '武装炼金',
    'Busou Renkin': '武装炼金',
    'Kekkaishi': '结界师',
    'Kekkaishi': '结界师',
    'Sousei no Aquarion': '创圣的大天使',
    'Aquarion': '创圣的大天使',
    'Genesis of Aquarion': '创圣的大天使',
    'Eureka Seven': '交响诗篇',
    'Koukyoushihen Eureka Seven': '交响诗篇',
    'Eureka Seven AO': '交响诗篇AO',
    'Tengen Toppa Gurren Lagann': '天元突破 红莲螺岩',
    'Gurren Lagann': '天元突破',
    'Kill la Kill': '斩服少女',
    'KLK': '斩服少女',
    'Promare': '普罗米亚',
    'Dead Leaves': '死亡之果',
    'FLCL': '特别的她',
    'Fooly Cooly': '特别的她',
    'Panty & Stocking with Garterbelt': '吊带袜天使',
    'Panty and Stocking': '吊带袜天使',
    'Space Dandy': '太空丹迪',
    'Cowboy Bebop': '星际牛仔',
    'Cowboy Bebop: Knockin\' on Heaven\'s Door': '星际牛仔：天国之门',
    'Samurai Champloo': '混沌武士',
    'Michiko to Hatchin': '道子与哈金',
    'Carole & Tuesday': '卡罗尔与星期二',
    'Kids on the Slope': '坂道上的阿波罗',
    'Sakamichi no Apollon': '坂道上的阿波罗',
    'Wandering Son': '放浪男孩',
    'Hourou Musuko': '放浪男孩',
    'Aoi Hana': '青之花',
    'Sweet Blue Flowers': '青之花',
    'Maria-sama ga Miteru': '圣母在上',
    'Maria Watches Over Us': '圣母在上',
    'Strawberry Panic!': '惊爆草莓',
    'Strawberry Panic': '惊爆草莓',
    'Sakura Trick': '樱Trick',
    'Sakura Trick': '樱Trick',
    'Citrus': 'citrus ～柑橘味香气～',
    'Citrus': 'citrus',
    'Bloom Into You': '终将成为你',
    'Yagate Kimi ni Naru': '终将成为你',
    'Adachi and Shimamura': '安达与岛村',
    'Adachi to Shimamura': '安达与岛村',
    'Otherside Picnic': '里世界郊游',
    'Ura Sekai Picnic': '里世界郊游',
    'The Executioner and Her Way of Life': '处刑少女的生存之道',
    'Shokei Shoujo no Virgin Road': '处刑少女的生存之道',
    'Lycoris Recoil': 'Lycoris Recoil',
    'Lycoris Recoil': '莉可丽丝',
    'Mahou Shoujo Tokushusen Asuka': '魔法少女特殊战明日香',
    'Magical Girl Spec-Ops Asuka': '魔法少女特殊战明日香',
    'Fate/kaleid liner Prisma☆Illya': '魔法少女☆伊莉雅',
    'Fate/kaleid liner Prisma Illya': '魔法少女☆伊莉雅',
    'Mahou Shoujo Lyrical Nanoha': '魔法少女奈叶',
    'Magical Girl Lyrical Nanoha': '魔法少女奈叶',
    'Mahou Shoujo Madoka Magica: Magia Record': '魔法纪录 魔法少女小圆外传',
    'Magia Record': '魔法纪录',
    'Cardcaptor Sakura': '魔卡少女樱',
    'CCS': '魔卡少女樱',
    'Cardcaptor Sakura: Clear Card-hen': '魔卡少女樱 透明牌篇',
    'Tokyo Mew Mew': '东京猫猫',
    'Tokyo Mew Mew New': '东京猫猫 NEW～♡',
    'Shugo Chara!': '守护甜心',
    'My Guardian Characters': '守护甜心',
    'Pretty Cure': '光之美少女',
    'Precure': '光之美少女',
    'Hirogaru Sky! Precure': '开阔天空！光之美少女',
    'Delicious Party♡Precure': 'Delicious Party♡光之美少女',
    'Tropical-Rouge! Precure': 'Tropical-Rouge!光之美少女',
    'Healin\' Good♥Precure': 'Healin\' Good♥光之美少女',
    'Star☆Twinkle Precure': 'Star☆Twinkle光之美少女',
    'Hugtto! Precure': 'Hugtto!光之美少女',
    'KiraKira☆Precure A La Mode': 'KiraKira☆光之美少女 A La Mode',
    'Maho Girls Precure!': '魔法使光之美少女',
    'Go! Princess Precure': 'Go! Princess 光之美少女',
    'HappinessCharge Precure!': 'HappinessCharge光之美少女！',
    'Dokidoki! Precure': '心跳！光之美少女',
    'Smile Precure!': '微笑光之美少女！',
    'Suite Precure♪': 'Suite 光之美少女♪',
    'HeartCatch Precure!': 'HeartCatch光之美少女！',
    'Fresh Precure!': 'FRESH光之美少女！',
    'Yes! Precure 5 GoGo!': 'Yes! 光之美少女5 GoGo!',
    'Yes! Precure 5': 'Yes! 光之美少女5',
    'Futari wa Precure Splash Star': '光之美少女Splash Star',
    'Futari wa Precure Max Heart': '光之美少女 Max Heart',
    'Futari wa Precure': '光之美少女',
    'Aikatsu!': '偶像活动！',
    'Aikatsu Stars!': '偶像活动Stars！',
    'Aikatsu Friends!': '偶像活动Friends！',
    'Aikatsu on Parade!': '偶像活动 on Parade！',
    'Aikatsu Planet!': '偶像活动Planet！',
    'Waccha PriMagi!': '美妙魔法！',
    'Kiratto Pri☆Chan': '美妙频道',
    'Idol Time PriPara': '偶像时间 美妙天堂',
    'PriPara': '美妙天堂',
    'Pretty Rhythm: Aurora Dream': '美妙旋律 极光之梦',
    'Pretty Rhythm: Dear My Future': '美妙旋律 亲爱的我的未来',
    'Pretty Rhythm: Rainbow Live': '美妙旋律 Rainbow Live',
    'King of Prism': '棱镜少男',
    'King of Prism by PrettyRhythm': '棱镜少男',
    'King of Prism: Pride the Hero': '棱镜少男 KING OF PRISM PRIDE THE HERO',
    'BanG Dream!': 'BanG Dream! 少女乐团派对',
    'BanG Dream! Girls Band Party!': 'BanG Dream! 少女乐团派对',
    'BanG Dream! Poppin\' Dream!': 'BanG Dream! Poppin\'Dream!',
    'D4DJ First Mix': 'D4DJ First Mix',
    'D4DJ Petit Mix': 'D4DJ Petit Mix',
    'D4DJ All Mix': 'D4DJ All Mix',
    'Love Live! School Idol Project': 'Love Live! 学园偶像计划',
    'Love Live!': 'Love Live!',
    'Love Live! School Idol Project 2nd Season': 'Love Live! 学园偶像计划 第二季',
    'Love Live! The School Idol Movie': 'Love Live! 学园偶像电影',
    'Love Live! Sunshine!!': 'Love Live! Sunshine!!',
    'Love Live! Sunshine!! 2nd Season': 'Love Live! Sunshine!! 第二季',
    'Love Live! Sunshine!! The School Idol Movie: Over the Rainbow': 'Love Live! Sunshine!! 学园偶像电影～彩虹彼端～',
    'Love Live! Nijigasaki High School Idol Club': 'Love Live! 虹咲学园学园偶像同好会',
    'Love Live! Nijigasaki High School Idol Club 2nd Season': 'Love Live! 虹咲学园学园偶像同好会 第二季',
    'Love Live! Nijigasaki High School Idol Club NEXT SKY': 'Love Live! 虹咲学园学园偶像同好会 NEXT SKY',
    'Love Live! Superstar!!': 'Love Live! Superstar!!',
    'Love Live! Superstar!! 2nd Season': 'Love Live! Superstar!! 第二季',
    'Love Live! Superstar!! 3rd Season': 'Love Live! Superstar!! 第三季',
    'Liella!': 'Liella!',
    'Nijigasaki': '虹咲',
    'Aqours': 'Aqours',
    'μ\'s': '缪斯',
    'Umi Sonoda': '园田海未',
    'Kotori Minami': '南小鸟',
    'Maki Nishikino': '西木野真姬',
    'Rin Hoshizora': '星空凛',
    'Hanayo Koizumi': '小泉花阳',
    'Nico Yazawa': '矢泽妮可',
    'Eli Ayase': '绚濑绘里',
    'Nozomi Tojo': '东条希',
    'Chika Takami': '高海千歌',
    'Riko Sakurauchi': '樱内梨子',
    'You Watanabe': '渡边曜',
    'Yoshiko Tsushima': '津岛善子',
    'Hanamaru Kunikida': '国木田花丸',
    'Ruby Kurosawa': '黑泽露比',
    'Dia Kurosawa': '黑泽黛雅',
    'Kanan Matsuura': '松浦果南',
    'Mari Ohara': '小原鞠莉',
    'Ayumu Uehara': '上原步梦',
    'Kasumi Nakasu': '中须霞',
    'Shizuku Osaka': '樱坂雫',
    'Karin Asaka': '朝香果林',
    'Mia Taylor': '米雅·泰勒',
    'Rina Tennoji': '天王寺璃奈',
    'Ai Miyashita': '宫下爱',
    'Kanata Konoe': '近江彼方',
    'Emma Verde': '艾玛·维尔德',
    'Setsuna Yuki': '优木雪菜',
    'Shioriko Mifune': '三船栞子',
    'Lanzhu Zhong': '钟岚珠',
    'Kanon Shibuya': '涩谷香音',
    'Keke Tang': '唐可可',
    'Chisato Arashi': '岚千砂都',
    'Sumire Heanna': '平安名堇',
    'Ren Hazuki': '叶月恋',
    'Kinako Sakurakoji': '樱小路希奈子',
    'Mei Yoneme': '米女芽衣',
    'Natsumi Onitsuka': '鬼冢夏美',
    'Li Mei': '李米酱',
    'Wien Margarete': '维恩·玛格丽特',
    'Tomari Onitsuka': '鬼冢冬毬',
    'Poppin\'Party': 'Poppin\'Party',
    'Roselia': 'Roselia',
    'Afterglow': 'Afterglow',
    'Pastel*Palettes': 'Pastel*Palettes',
    'Hello, Happy World!': 'Hello, Happy World!',
    'Morfonica': 'Morfonica',
    'RAISE A SUILEN': 'RAISE A SUILEN',
    'MyGO!!!!!': 'MyGO!!!!!',
    'Ave Mujica': 'Ave Mujica',
    'Kasumi Toyama': '户山香澄',
    'Tae Hanazono': '花园多惠',
    'Rimi Ushigome': '牛込里美',
    'Saya Yamabuki': '山吹沙绫',
    'Arisa Ichigaya': '市谷有咲',
    'Rinko Shirokane': '白金燐子',
    'Ako Udagawa': '宇田川亚子',
    'Lisa Imai': '今井莉莎',
    'Yukina Minato': '凑友希那',
    'Sayo Hikawa': '冰川纱夜',
    'Tomoe Udagawa': '宇田川巴',
    'Moca Aoba': '青叶摩卡',
    'Himari Uehara': '上原绯玛丽',
    'Ran Mitake': '美竹兰',
    'Tsugumi Hazawa': '羽泽鸫',
    'Eve Wakamiya': '若宫伊芙',
    'Hina Hikawa': '冰川日菜',
    'Maya Yamato': '大和麻弥',
    'Chisato Shirasagi': '白鹭千圣',
    'Hagumi Kitazawa': '北泽育美',
    'Kokoro Tsurumaki': '弦卷心',
    'Kaoru Seta': '濑田薰',
    'Mashiro Kurata': '仓田真白',
    'Toko Kirigaya': '桐谷透子',
    'Nanami Hiromachi': '广町七深',
    'Tsukushi Futaba': '二叶筑紫',
    'Rui Yashio': '八潮瑠唯',
    'Rei Wakana': '和奏瑞依',
    'Masuki Satou': '佐藤增姬',
    'Nyubara Reona': '珠手知由',
    'PAREO': 'PAREO',
    'CHU²': 'CHU²',
    'Tomori Takamatsu': '高松灯',
    'Anon Chihaya': '千早爱音',
    'Rāna Kaname': '要乐奈',
    'Soyo Nagasaki': '长崎爽世',
    'Taki Shiina': '椎名立希',
    'Uika Misumi': '三角初华',
    'Sakiko Togawa': '丰川祥子',
    'Mutsumi Wakaba': '若叶睦',
    'Umiri Yahata': '八幡海铃',
    'Mortis': 'Mortis',
    'Oblivionis': 'Oblivionis',
    'Väinämöinen': 'Väinämöinen',
    'Timoris': 'Timoris',
    'Amoris': 'Amoris',
    'Shiori': '诗织',
    'Ako': '亚子',
    'Moca': '摩卡',
    'Himari': '绯玛丽',
    'Tsugumi': '鸫',
    'Hina': '日菜',
    'Maya': '麻弥',
    'Chisato': '千圣',
    'Hagumi': '育美',
    'Kokoro': '心',
    'Kaoru': '薰',
    'Mashiro': '真白',
    'Toko': '透子',
    'Nanami': '七深',
    'Tsukushi': '筑紫',
    'Rui': '瑠唯',
    'Rei': '瑞依',
    'Masuki': '增姬',
    'Reona': '知由',
    'Tomori': '灯',
    'Anon': '爱音',
    'Rāna': '乐奈',
    'Soyo': '爽世',
    'Taki': '立希',
    'Uika': '初华',
    'Sakiko': '祥子',
    'Mutsumi': '睦',
    'Umiri': '海铃',
    'Kasumi': '香澄',
    'Tae': '多惠',
    'Rimi': '里美',
    'Saya': '沙绫',
    'Arisa': '有咲',
    'Rinko': '燐子',
    'Lisa': '莉莎',
    'Yukina': '友希那',
    'Sayo': '纱夜',
    'Tomoe': '巴',
    'Ran': '兰',
    'Eve': '伊芙',
    'Hikawa': '冰川',
    'Udagawa': '宇田川',
    'Shirokane': '白金',
    'Minato': '凑',
    'Mitake': '美竹',
    'Uehara': '上原',
    'Kitazawa': '北泽',
    'Tsurumaki': '弦卷',
    'Seta': '濑田',
    'Kurata': '仓田',
    'Kirigaya': '桐谷',
    'Hiromachi': '广町',
    'Futaba': '二叶',
    'Yashio': '八潮',
    'Wakana': '和奏',
    'Satou': '佐藤',
    'Nyubara': '珠手',
    'Takamatsu': '高松',
    'Chihaya': '千早',
    'Kaname': '要',
    'Nagasaki': '长崎',
    'Shiina': '椎名',
    'Misumi': '三角',
    'Togawa': '丰川',
    'Wakaba': '若叶',
    'Yahata': '八幡',
    'PoppinParty': 'Poppin\'Party',
    'RAS': 'RAS',
    'Argonavis': 'Argonavis',
    'GYROAXIA': 'GYROAXIA',
    'Fantôme Iris': 'Fantôme Iris',
    'Fuze!!': 'Fuze!!',
    'Bakumatsu Rock': '幕末Rock',
    'Samurai Jam -Bakumatsu Rock-': '幕末Rock',
    'Show By Rock!!': 'Show By Rock!!',
    'SB69': 'SB69',
    'Sanrio': '三丽鸥',
    'Hello Kitty': '凯蒂猫',
    'Cinnamoroll': '玉桂狗',
    'My Melody': '美乐蒂',
    'Kuromi': '酷洛米',
    'Pompompurin': '布丁狗',
    'Keroppi': '大眼蛙',
    'Tuxedo Sam': '山姆企鹅',
    'Badtz-Maru': '酷企鹅',
    'Hangyodon': '人鱼汉顿',
    'Little Twin Stars': '双子星',
    'Sugarbunnies': '蜜糖邦尼',
    'Jewelpet': '宝石宠物',
    'Rilu Rilu Fairilu': '莉露莉露妖精莉露',
    'Lilpri': '变身！偶像公主',
    'PriPri Chii-chan!!': 'PriPri Chi-chan!!',
    'Mewkledreamy': '甜梦猫',
    'Mewkledreamy Mix!': '甜梦猫 Mix！',
    'Idolish7': 'IDOLiSH7',
    'Idolish7 Vibrato': 'IDOLiSH7 Vibrato',
    'Idolish7 Second Beat!': 'IDOLiSH7 Second BEAT!',
    'Idolish7 Third Beat!': 'IDOLiSH7 Third BEAT!',
    'Trigger': 'TRIGGER',
    'Re:vale': 'Re:vale',
    'ZOOL': 'ZOOL',
    'Iori Izumi': '和泉一织',
    'Yamato Nikaidou': '二阶堂大和',
    'Mitsuki Izumi': '和泉三月',
    'Tamaki Yotsuba': '四叶环',
    'Sogo Osaka': '逢坂壮五',
    'Nagi Rokuya': '六弥凪',
    'Riku Nanase': '七濑陆',
    'Gaku Yaotome': '八乙女乐',
    'Ten Kujou': '九条天',
    'Ryunosuke Tsunashi': '十龙之介',
    'Momo': '百',
    'Yuki': '千',
    'Toma Inumaru': '狗丸柊马',
    'Minami Natsume': '棗巳波',
    'Torao Midou': '御堂虎于',
    'Haruka Isumi': '亥清悠',
    'B-Project': 'B-PROJECT',
    'B-PROJECT~ Kodou*Ambitious': 'B-PROJECT～鼓动*Ambitious～',
    'B-PROJECT~ Zecchou*Emotion': 'B-PROJECT～绝顶*Emotion～',
    'B-Project~ Netsuretsu*Love Call': 'B-PROJECT～热烈*Love Call～',
    'KitaKore': 'KitaKore',
    'MooNs': 'MooNs',
    'THRIVE': 'THRIVE',
    'KiLLER KiNG': 'KiLLER KiNG',
    'Uta no Prince-sama': '歌之王子殿下',
    'Uta no Prince-sama Maji Love 1000%': '歌之王子殿下 真爱1000%',
    'Uta no Prince-sama Maji Love 2000%': '歌之王子殿下 真爱2000%',
    'Uta no Prince-sama Maji Love Revolutions': '歌之王子殿下 真爱革命',
    'Uta no Prince-sama Maji LOVE Legend Star': '歌之王子殿下 真爱Legend Star',
    'Uta no Prince-sama Maji LOVE Kingdom': '歌之王子殿下 真爱王国',
    'STARISH': 'ST☆RISH',
    'QUARTET NIGHT': 'QUARTET NIGHT',
    'HEAVENS': 'HE★VENS',
    'Otoya Ittoki': '一十木音也',
    'Tokiya Ichinose': '一之濑时矢',
    'Ren Jinguji': '神宫寺莲',
    'Natsuki Shinomiya': '四之宫那月',
    'Syo Kurusu': '来栖翔',
    'Masato Hijirikawa': '圣川真斗',
    'Cecil Aijima': '爱岛塞西尔',
    'Reiji Kotobuki': '寿岭二',
    'Ranmaru Kurosaki': '黑崎兰丸',
    'Ai Mikaze': '美风蓝',
    'Camus': '卡缪',
    'Shining Amamiya': '天草紫苑',
    'Kira Sumeragi': '皇绮罗',
    'Eiichi Otori': '凤瑛一',
    'Nagi Mikado': '帝凪',
    'Eiji Otori': '凤瑛二',
    'Van Kiryuin': '桐生院范',
    'Shion Amakusa': '天草紫苑',
    'Yamato Hyuga': '日向大和',
    'Tsukumo Orine': '织音',
    'Tsukiuta': '月歌',
    'Tsukiuta. The Animation': '月歌',
    'Tsukiuta. The Animation 2': '月歌2',
    'Six Gravity': 'Six Gravity',
    'Procellarum': 'Procellarum',
    'Fluna': 'Fluna',
    'Seleas': 'Seleas',
    'Kakeru Shiwasu': '师走驱',
    'Hajime Mutsuki': '睦月始',
    'Haru Yayoi': '弥生春',
    'Arata Uduki': '卯月新',
    'Koi Kisaragi': '如月恋',
    'Kakeru Shiwasu': '师走驱',
    'Iku Kannaduki': '神无月郁',
    'Rui Minaduki': '水无月泪',
    'Yoru Fuduki': '文月海',
    'You Haduki': '叶月阳',
    'Shun Shimotsuki': '霜月隼',
    'SideM': 'SideM',
    'The Idolm@ster SideM': '偶像大师 SideM',
    'The Idolm@ster SideM: Wake Atte Mini!': '偶像大师 SideM 有理由Mini！',
    '315 Production': '315 Production',
    '315pro': '315事务所',
    'DRAMATIC STARS': 'DRAMATIC STARS',
    'Beit': 'Beit',
    'S.E.M': 'S.E.M',
    'High×Joker': 'High×Joker',
    'W': 'W',
    'Altessimo': 'Altessimo',
    'Jupiter': 'Jupiter',
    'F-LAGS': 'F-LAGS',
    'Café Parade': 'Café Parade',
    'Mofumofuen': 'Mofumofuen',
    'The Kogado': 'The 虎牙道',
    'FRAME': 'FRAME',
    'Legenders': 'Legenders',
    'Shinsoku Ikkon': '神速一魂',
    'Xenon': 'Xenon',
    'THE IDOLM@STER CINDERELLA GIRLS': '偶像大师 灰姑娘女孩',
    'The Idolm@ster Cinderella Girls': '偶像大师 灰姑娘女孩',
    'Idolmaster: Cinderella Girls': '偶像大师 灰姑娘女孩',
    'The Idolm@ster Cinderella Girls Theater': '偶像大师 灰姑娘女孩剧场',
    '346 Production': '346 Production',
    '346pro': '346事务所',
    'Uzuki Shimamura': '岛村卯月',
    'Rin Shibuya': '涩谷凛',
    'Mio Honda': '本田未央',
    'Anzu Futaba': '双叶杏',
    'Ranko Kanzaki': '神崎兰子',
    'Minami Nitta': '新田美波',
    'Riina Tada': '多田李衣菜',
    'Airi Totoki': '十时爱梨',
    'Nana Abe': '安部菜菜',
    'Chieri Ogata': '绪方智绘里',
    'Karen Hojo': '北条加莲',
    'Kanako Mimura': '三村加奈子',
    'Sachiko Koshimizu': '舆水幸子',
    'Mika Jougasaki': '城崎美嘉',
    'Rika Jougasaki': '城崎莉嘉',
    'Miria Akagi': '赤城米莉亚',
    'Syoko Hoshi': '星辉子',
    'Yumi Aiba': '相叶夕美',
    'Ayame Hamaguchi': '滨口菖蒲',
    'Mayu Sakuma': '佐久间麻由',
    'Yukari Mizumoto': '水本紫',
    'Sae Kobayakawa': '小早川纱枝',
    'Kako Takafuji': '鹰富士茄子',
    'Natsuki Kimura': '木村夏树',
    'Yoshino Yorita': '依田芳乃',
    'Hina Araki': '荒木比奈',
    'Rina Fujimoto': '藤本里奈',
    'Eve Santaclaus': '伊芙·圣诞老人',
    'Akiha Igarashi': '五十岚响子',
    'Shizuku Oikawa': '及川雫',
    'Momoka Sakurai': '樱井桃华',
    'Shiori Shiomiya': '潮见香',
    'Tamami Wakiyama': '胁山珠美',
    'Haruna Kamijou': '上条春菜',
    'Kaoru Ryuzaki': '龙崎薰',
    'Chizuru Matsuo': '松尾千鹤',
    'Kyoko Igarashi': '五十岚响子',
    'Hiroe Sawa': '泽田麻理菜',
    'Sumire Saito': '斋藤堇',
    'Izumi Okami': '大神环',
    'Meiko Namiki': '并木芽衣子',
    'Saori Okuyama': '奥山沙织',
    'Akari Tsujino': '辻野朱里',
    'THE IDOLM@STER MILLION LIVE!': '偶像大师 百万现场',
    'The Idolm@ster Million Live!': '偶像大师 百万现场',
    'Idolmaster: Million Live!': '偶像大师 百万现场',
    '765 Million Stars': '765百万明星',
    'Mirai Kasuga': '春日未来',
    'Emily Stewart': '艾米丽·斯图尔特',
    'Konomi Baba': '马场木实',
    'Roco': 'ROCO',
    'Julia': 'JULIA',
    'Tsumugi Shiraishi': '白石紬',
    'Shizuka Mogami': '最上静香',
    'Megumi Tokoro': '所惠美',
    'Rena Hyodo': '兵藤丽奈',
    'Karen Shinomiya': '筱宫可怜',
    'Sayoko Takayama': '高山纱代子',
    'Mitsuki Kikuchi': '菊地真',
    'Makoto Kikuchi': '菊地真',
    'Iori Minase': '水濑伊织',
    'Yayoi Takatsuki': '高槻弥生',
    'Takane': '贵音',
    'Hibiki': '响',
    'Miki': '美希',
    'Chihaya': '千早',
    'Azusa': '梓',
    'Ami': '亚美',
    'Mami': '真美',
    'Ritsuko': '律子',
    'Hinata': '日向',
    'Kana': '加奈',
    'Noriko': '法子',
    'Miyako': '都',
    'Kei': '慧',
    'Rio': '莉绪',
    'Nanoha': '乃乃',
    'Chizuru': '千鹤',
    'Kyouko': '杏子',
    'Reika': '玲香',
    'Sora': '空',
    'Shiho': '志保',
    'Ayumu': '歩',
    'Seira': '星罗',
    'Kotoha': '琴叶',
    'Tomoka': '朋花',
    'Momoko': '桃子',
    'Arisa': '亚里沙',
    'Umi': '海美',
    'Mizuki': '瑞希',
    'Fuka': '风华',
    'Matsuri': '茉莉',
    'Serika': 'Serika',
    'Miho': 'Miho',
    'Nao': '奈绪',
    'Hana': 'Hana',
    'Aoi': 'Aoi',
    'Sumire': '堇',
    'Natalia': '娜塔莉亚',
    'Alicia': '艾丽西亚',
    'Ryoka': '凉香',
    'Yukiko': '雪子',
    'THE iDOLM@STER: Shiny Colors': '偶像大师 闪耀色彩',
    'The Idolm@ster Shiny Colors': '偶像大师 闪耀色彩',
    'Idolmaster: Shiny Colors': '偶像大师 闪耀色彩',
    '283 Production': '283 Production',
    '283pro': '283事务所',
    'Illumination STARS': 'ILLUMINATION STARS',
    'L\'Antica': 'L'Antica',
    'ALSTROEMERIA': 'ALSTROEMERIA',
    'Straylight': 'Straylight',
    'noctchill': 'noctchill',
    'Houkago Climax Girls': '放课后C/G',
    'Mano Sakuragi': '樱木真乃',
    'Hana Suzuki': '铃木羽那',
    'Kiriko Yuyama': '幽谷雾子',
    'Mamimi Tanaka': '田中摩美美',
    'Toru Asakura': '浅仓透',
    'Yukoku Kiriko': '幽谷霧子',
    'Koito Fukumaru': '福丸小糸',
    'Natsuha Arisugawa': '有栖川夏叶',
    'Madoka Higuchi': '樋口圆香',
    'Rinze Morino': '森野莉子',
    'Juri Saijo': '西城树里',
    'Chiyuki Kuwayama': '桑山千雪',
    'Asahi Serizawa': '芹泽朝阳',
    'Fuyuko Mayuzumi': '黛冬优子',
    'Mei Izumi': '和泉爱依',
    'Nichika Nanakusa': '七草日花',
    'Kaho Komiya': '小宫果穗',
    'Saying Koshimizu': 'Saying Koshimizu',
    'Hinata Shiraishi': '白石日向',
    'Amana Osaki': '大崎甘奈',
    'Tenka Osaki': '大崎甜花',
    'Chiro': '千路',
    'Luca': 'Luca',
    'THE IDOLM@STER': '偶像大师',
    '765 Production': '765 Production',
    '765pro': '765事务所',
    'Haruka Amami': '天海春香',
    'Chihaya Kisaragi': '如月千早',
    'Miki Hoshii': '星井美希',
    'Yukiho Hagiwara': '萩原雪步',
    'Yayoi Takatsuki': '高槻弥生',
    'Ritsuko Akizuki': '秋月律子',
    'Azusa Miura': '三浦梓',
    'Iori Minase': '水濑伊织',
    'Makoto Kikuchi': '菊地真',
    'Ami Futami': '双海亚美',
    'Mami Futami': '双海真美',
    'Hibiki Ganaha': '我那霸响',
    'Takane Shijou': '四条贵音',
    'Ryo Akizuki': '秋月凉',
    'Ai Hidaka': '日高爱',
    'Eri Mizutani': '水谷绘理',
    'Ayane Suzuki': '铃木彩音',
    'Konomi Watanabe': '渡边公美',
    'Yuuna Kashiwagi': '柏木由奈',
    'Kana Yabuki': '矢吹可奈',
    'Minako Satake': '佐竹美奈子',
    'Noriko Fukuda': '福田法子',
    'Miyako Anzai': '安西都',
    'Nao Yokoyama': '横山奈绪',
    'Kotoha Tanaka': '田中琴叶',
    'Megumi Matsumoto': '松本惠',
    'Roco Handa': '伴田路子',
    'Arisa Matsuda': '松田亚利沙',
    'Umi Kousaka': '高坂海美',
    'Mizuki Makabe': '真壁瑞希',
    'Karen Shinjo': '新城刊',
    'Fuka Toyokawa': '丰川风花',
    'Emily': '艾米丽',
    'Julia': '朱莉娅',
    'Tsumugi': '紬',
    'Shizuka': '静香',
    'Tamaki': '珠树',
    'Aine': '爱音',
    'Mio': '未央',
    'Kaede': '枫',
    'Hazuki': '叶月',
    'Suzuka': '凉风',
    'Miyabi': '雅',
    'Kurumi': '胡桃',
    'Matsuri': '祭',
    'Hotaru': '萤',
    'Sumire': '堇',
    'Kana': '香菜',
    'Saori': '沙织',
    'Erika': '绘梨花',
    'Akane': '茜',
    'Sora': '天',
    'Tsubasa': '翼',
    'Otowa': '乙羽',
    'Rei': '怜',
    'Juri': '寿',
    'Mahiro': '真寻',
    'Chiyo': '千代',
    'Noel': '诺爱尔',
    'Futaba': '双叶',
    'Hana': '花子',
    'Momo': '百子',
    'Miho': '美帆',
    'Airi': '爱理',
    'Mayu': '真由',
    'Saya': '沙绫',
    'Yui': '唯',
    'Rio': '莉央',
    'Hinako': '雏子',
    'Kinako': '黄粉',
    'Shinobu': '忍',
    'Nagisa': '渚',
    'Kokoro': '心',
    'Misaki': '美咲',
    'Risa': '理沙',
    'Erena': '惠令奈',
    'Ayumi': '步',
    'Sayuki': '雪',
    'Rui': '泪',
    'Yuriko': '百合子',
    'Yuko': '裕子',
    'Miya': '美也',
    'Mina': '美菜',
    'Chizuru': '千鹤',
    'Asuka': '飞鸟',
    'Keiko': '惠子',
    'Naoko': '直子',
    'Yukino': '雪乃',
    'Meika': '明香',
    'Satomi': '聪美',
    'Rochin': '露草',
    'Nao': '奈绪',
    'Sana': '纱名',
    'Luka': 'ルカ',
    'Monica': '莫妮卡',
    'Sakurako': '樱子',
    'Yuno': 'ユノ',
    'Akari': '朱莉',
    'Miria': '米莉亚',
    'Anastasia': '安娜史塔西亚',
    'Katagiri': '片桐',
    'Sora': '空',
    'Minako': '美奈子',
    'Yoshimi': '好美',
    'Aki': '亚季',
    'Puchimasu!': '迷你偶像',
    'Puchimas! Petit Idolmaster': '迷你偶像',
    'Wake Up, Girls!': 'Wake Up, Girls!',
    'Wake Up, Girls! 2': 'Wake Up, Girls! 新章',
    'Wake Up, Girls! Beyond the Bottom': 'Wake Up, Girls! 超越深限',
    'I-1 Club': 'I-1 Club',
    'Run Girls, Run!': 'Run Girls, Run!',
    'Coco Kirishima': '桐岛可可',
    'Rei Kagura': '神乐丽',
    'Megu Uehara': '上原芽衣',
    'Episode of Lisa': 'Episode of Lisa',
    'Idol Bu Show': '偶像狂骚曲',
    'Idol Bu Show': '偶像部',
    'Idol Densetsu Eriko': '偶像传说英里子',
    'Idol Angel Yokoso Yoko': '偶像天使阳子',
    'Idol Defense Force Hummingbird': '偶像防卫队',
    'NEXT INNOVATION': '次世代创新',
    'Idolmaster Xenoglossia': '偶像大师 XENOGLOSSIA',
    'Idolm@ster Xenoglossia': '偶像大师 XENOGLOSSIA',
    'iDOLM@STER Xenoglossia': '偶像大师 XENOGLOSSIA',
    'Munday Manyūchō Kitan Yajikita': 'Munday Manyūchō Kitan Yajikita',
    'Key': 'Key',
    'Visual Art\'s': 'Visual Art\'s',
    'KyoAni': '京阿尼',
    'Kyoto Animation': '京都动画',
    'P.A.Works': 'P.A.Works',
    'J.C.Staff': 'J.C.Staff',
    'Shaft': 'SHAFT',
    'ufotable': 'ufotable',
    'Madhouse': 'MADHOUSE',
    'Production I.G': 'Production I.G',
    'Bones': 'BONES',
    'Wit Studio': 'WIT STUDIO',
    'CloverWorks': 'CloverWorks',
    'A-1 Pictures': 'A-1 Pictures',
    'Aniplex': 'Aniplex',
    'Bandai Namco': '万代南梦宫',
    'Sunrise': '日升',
    'Toei Animation': '东映动画',
    'Gainax': 'GAINAX',
    'Trigger': 'TRIGGER',
    'Khara': 'Khara',
    'Studio 4°C': 'STUDIO 4℃',
    'Science SARU': 'Science SARU',
    'Masaaki Yuasa': '汤浅政明',
    'Makoto Shinkai': '新海诚',
    'Hayao Miyazaki': '宫崎骏',
    'Isao Takahata': '高畑勋',
    'Hideaki Anno': '庵野秀明',
    'Kunihiko Ikuhara': '几原邦彦',
    'Mamoru Oshii': '押井守',
    'Satoshi Kon': '今敏',
    'Yoshiyuki Tomino': '富野由悠季',
    'Shoji Kawamori': '河森正治',
    'Gen Urobuchi': '虚渊玄',
    'Mari Okada': '冈田麿里',
    'Nisio Isin': '西尾维新',
    'Kinoko Nasu': '奈须蘑菇',
    'Urobuchi Gen': '虚渊玄',
    'Type-Moon': '型月',
    'TYPE-MOON': 'TYPE-MOON',
    'Nasu Kinoko': '奈须きのこ',
    'Takeuchi Takashi': '武内崇',
    'Fate Series': 'Fate系列',
    'Tsukihime': '月姬',
    'Kara no Kyoukai': '空之境界',
    'Garden of Sinners': '空之境界',
    'Mahoutsukai no Yoru': '魔法使之夜',
    'Witch on the Holy Night': '魔法使之夜',
    'Melty Blood': '月姬格斗',
    'Fate/stay night': '命运之夜',
    'Fate/stay night [Unlimited Blade Works]': '命运之夜 无限剑制',
    'Fate/stay night: Heaven\'s Feel': '命运之夜 天之杯',
    'Fate/Zero': '命运零点',
    'Fate/Apocrypha': '命运外典',
    'Fate/Grand Order': '命运冠位指定',
    'Fate/Grand Order: First Order': '命运冠位指定 第一特典',
    'Fate/Grand Order: Moonlight/Lostroom': '命运冠位指定 月光/失落之室',
    'Fate/Grand Order: Zettai Majuu Sensen Babylonia': '命运冠位指定 绝对魔兽战线巴比伦尼亚',
    'Fate/Grand Order: Shinsei Entaku Ryouiki Camelot': '命运冠位指定 神圣圆桌领域卡美洛',
    'Fate/Grand Order: Shuukyoku Tokuiten - Kani Jikan Shinden Solomon': '命运冠位指定 终局特异点 冠位时间神殿所罗门',
    'Fate/Grand Carnival': '命运冠位嘉年华',
    'Fate/Prototype': 'Fate/Prototype',
    'Fate/Prototype: Sougin no Fragments': 'Fate/Prototype 苍银的碎片',
    'Fate/EXTRA': 'Fate/EXTRA',
    'Fate/EXTRA Last Encore': '命运/异章 最终回响',
    'Fate/EXTRA CCC': 'Fate/EXTRA CCC',
    'Fate/Extella': 'Fate/EXTELLA',
    'Fate/Extella Link': 'Fate/EXTELLA LINK',
    'Fate/kaleid liner': '魔法少女☆伊莉雅',
    'Lord El-Melloi II Sei no Jikenbo': '君主·埃尔梅罗二世事件簿',
    'The Case Files of Lord El-Melloi II': '君主·埃尔梅罗二世事件簿',
    'Fate/strange fake': 'Fate/strange fake',
    'Fate/Samurai Remnant': 'Fate/Samurai Remnant',
    'Saber': '阿尔托莉雅·潘德拉贡',
    'Altria Pendragon': '阿尔托莉雅·潘德拉贡',
    'Artoria Pendragon': '阿尔托莉雅·潘德拉贡',
    'King Arthur': '亚瑟王',
    'Rider': '骑兵',
    'Lancer': '枪兵',
    'Archer': '弓兵',
    'Berserker': '狂战士',
    'Assassin': '暗杀者',
    'Caster': '魔术师',
    'Shielder': '盾兵',
    'Ruler': '裁定者',
    'Avenger': '复仇者',
    'Alter Ego': '他人格',
    'Moon Cancer': '月之癌',
    'Foreigner': '降临者',
    'Pretender': '伪装者',
    'Saber Alter': '阿尔托莉雅·潘德拉贡〔Alter〕',